# Generated by Django 4.0.4 on 2022-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfpwithfriends', '0008_pfp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfp',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
